export type CategoriaCorte = "economico" | "mixto" | "premium";
export type TipoCarne = "vacuno" | "cerdo" | "pollo" | "embutidos";
export type FormatoCompra = "peso_variable" | "bandeja" | "pack" | "unidad";
export type UnidadPrecio = "kg" | "pack" | "unidad";

// null = composición ósea no resuelta para una referencia genérica o histórica.
// factorCompra convierte la demanda base a peso de compra SOLO cuando exista una
// corrección comercial explícitamente validada. Como la demanda base ya está
// definida en peso crudo de compra (AP), los productos con hueso quedan en 1.0
// hasta contar con una calibración propia que no mezcle hueso + cocción + grasa.

export interface ProductoAsado {
  id: string;
  nombre: string;
  tipo: TipoCarne;
  precio: number;

  // Trazabilidad del precio de referencia usado por la calculadora.
  // fechaPrecio = fecha en que se revisó la referencia comercial.
  fechaPrecio?: string;
  fuentePrecio?: string;
  referenciaPrecio?: string;

  parrilla: boolean;
  conHueso: boolean | null;
  factorCompra?: number;
  categoria: CategoriaCorte;
  unidadPrecio: UnidadPrecio;
  formatoCompra: FormatoCompra;
  pesoFormatoKg?: number;
  pesoMinimo?: number;
  pesoPromedio?: number;
  pesoMaximo?: number;
  unidadesPorPack?: number;
  descripcionVenta?: string;
}

export interface ProductosAsado {
  vacuno: ProductoAsado[];
  cerdo: ProductoAsado[];
  pollo: ProductoAsado[];
  embutidos: ProductoAsado[];
}

/**
 * Política de precios de referencia:
 * - revisión comercial: 2026-10-09;
 * - fuente principal: Lider.cl;
 * - se privilegia precio regular/lista para evitar promociones temporales;
 * - cuando el producto se vende en pack de peso fijo y la fuente publica
 *   precio por pack, `precio` conserva $/pack y `pesoFormatoKg` el peso real;
 * - referencias genéricas sin equivalente suficientemente claro conservan
 *   su valor anterior y no declaran fuente/fecha hasta una revisión exacta.
 */
export const FECHA_REVISION_PRECIOS = "2026-10-09";

export const productosAsado: ProductosAsado = {
  vacuno: [
    {
      id: "vacuno-lomo-vetado",
      nombre: "Lomo vetado al vacío",
      tipo: "vacuno",
      precio: 17290,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Lomo Vetado · $17.290/kg",
      parrilla: true,
      conHueso: false,
      categoria: "premium",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 1.8,
      pesoMaximo: 2.5,
      descripcionVenta: "Pieza al vacío",
    },
    {
      id: "vacuno-lomo-liso",
      nombre: "Lomo liso al vacío",
      tipo: "vacuno",
      precio: 16390,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Lomo Liso · $16.390/kg",
      parrilla: true,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 1.7,
      pesoMaximo: 2.3,
      descripcionVenta: "Pieza al vacío",
    },
    {
      id: "vacuno-sobrecostilla",
      nombre: "Sobrecostilla",
      tipo: "vacuno",
      precio: 10190,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Sobrecostilla · $10.190/kg",
      parrilla: true,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.1,
      pesoMaximo: 1.5,
      descripcionVenta: "Bandeja o trozo",
    },
    {
      id: "vacuno-huachalomo",
      nombre: "Huachalomo",
      tipo: "vacuno",
      precio: 10190,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Huachalomo · $10.190/kg",
      parrilla: true,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.2,
      pesoMaximo: 1.6,
      descripcionVenta: "Bandeja o trozo",
    },
    {
      id: "vacuno-asado-carnicero",
      nombre: "Asado del carnicero",
      tipo: "vacuno",
      precio: 10190,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Asado Carnicero · $10.190/kg",
      parrilla: true,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.9,
      pesoPromedio: 1.3,
      pesoMaximo: 1.8,
      descripcionVenta: "Trozo para parrilla",
    },
    {
      id: "vacuno-punta-picana",
      nombre: "Punta picana",
      tipo: "vacuno",
      precio: 13690,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Punta de Picana · $13.690/kg",
      parrilla: true,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.5,
      pesoMaximo: 2.0,
      descripcionVenta: "Pieza entera o media pieza",
    },
    {
      id: "vacuno-filete",
      nombre: "Filete",
      tipo: "vacuno",
      precio: 17990,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Filete · precio regular $17.990/kg",
      parrilla: true,
      conHueso: false,
      categoria: "premium",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.6,
      pesoMaximo: 2.1,
      descripcionVenta: "Pieza al vacío",
    },
    {
      id: "vacuno-punta-ganso",
      nombre: "Punta de ganso",
      tipo: "vacuno",
      precio: 13990,
      parrilla: true,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.4,
      pesoMaximo: 1.9,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "vacuno-entrana",
      nombre: "Entraña",
      tipo: "vacuno",
      precio: 18390,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Entraña · $18.390/kg",
      parrilla: true,
      conHueso: false,
      categoria: "premium",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.4,
      pesoPromedio: 0.7,
      pesoMaximo: 1.0,
      descripcionVenta: "Bandeja o pieza delgada",
    },
    {
      id: "vacuno-tapabarriga",
      nombre: "Tapabarriga",
      tipo: "vacuno",
      precio: 11990,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Tapabarriga · $11.990/kg",
      parrilla: true,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.2,
      pesoMaximo: 1.6,
      descripcionVenta: "Trozo para parrilla",
    },
    {
      id: "vacuno-choclillo",
      nombre: "Choclillo",
      tipo: "vacuno",
      precio: 10990,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Choclillo · $10.990/kg",
      parrilla: false,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.6,
      pesoMaximo: 2.2,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "vacuno-ganso",
      nombre: "Ganso",
      tipo: "vacuno",
      precio: 9890,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Ganso · $9.890/kg",
      parrilla: false,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.1,
      pesoPromedio: 1.8,
      pesoMaximo: 2.5,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "vacuno-posta-rosada",
      nombre: "Posta rosada",
      tipo: "vacuno",
      precio: 11990,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Posta Rosada · $11.990/kg",
      parrilla: false,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.7,
      pesoMaximo: 2.3,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "vacuno-asiento",
      nombre: "Asiento",
      tipo: "vacuno",
      precio: 14590,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Asiento · precio regular $14.590/kg",
      parrilla: false,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.1,
      pesoPromedio: 1.8,
      pesoMaximo: 2.4,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "vacuno-plateada",
      nombre: "Plateada",
      tipo: "vacuno",
      precio: 11090,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Plateada · $11.090/kg",
      parrilla: false,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.6,
      pesoMaximo: 2.1,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "vacuno-tapapecho",
      nombre: "Tapapecho",
      tipo: "vacuno",
      precio: 10390,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Tapapecho · precio regular $10.390/kg",
      parrilla: false,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 2.0,
      pesoMaximo: 2.8,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "vacuno-punta-paleta",
      nombre: "Punta paleta",
      tipo: "vacuno",
      precio: 10690,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Punta de Paleta · $10.690/kg",
      parrilla: true,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.6,
      pesoMaximo: 2.2,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "vacuno-posta-negra",
      nombre: "Posta negra",
      tipo: "vacuno",
      precio: 11990,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Al Vacío · Carne de Vacuno Posta Negra · precio regular $11.990/kg",
      parrilla: false,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.7,
      pesoMaximo: 2.3,
      descripcionVenta: "Trozo entero",
    },
  ],

  cerdo: [
    {
      id: "cerdo-costillar",
      nombre: "Costillar de cerdo",
      tipo: "cerdo",
      precio: 9890,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Buen Corte · Costillar de Cerdo Chileno · precio regular $9.890/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 1.8,
      pesoMaximo: 2.5,
      descripcionVenta: "Costillar entero o medio costillar",
    },
    {
      id: "cerdo-lomo",
      nombre: "Lomo de cerdo",
      tipo: "cerdo",
      precio: 8990,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Cerdo · Lomo Centro 800 g · precio regular $7.190/pack ≈ $8.988/kg",
      parrilla: true,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.5,
      pesoMaximo: 2.0,
      descripcionVenta: "Pieza entera",
    },
    {
      id: "cerdo-malaya",
      nombre: "Malaya de cerdo",
      tipo: "cerdo",
      precio: 14878,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Cerdo · Malaya 900 g · $13.390/pack = $14.878/kg",
      parrilla: true,
      conHueso: false,
      categoria: "premium",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.2,
      pesoMaximo: 1.6,
      descripcionVenta: "Bandeja o trozo",
    },
    {
      id: "cerdo-chuleta-vetada",
      nombre: "Chuleta vetada",
      tipo: "cerdo",
      precio: 8950,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Pampaverde · Chuleta vetada 200 g · precio regular $1.790/pack = $8.950/kg",
      parrilla: true,
  conHueso: null,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.7,
      pesoPromedio: 1.0,
      pesoMaximo: 1.4,
      descripcionVenta: "Bandeja de chuletas",
    },
    {
      id: "cerdo-chuleta-centro",
      nombre: "Chuleta centro",
      tipo: "cerdo",
      precio: 8891,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Cerdo · Chuleta centro 550 g · precio regular $4.890/pack ≈ $8.891/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.7,
      pesoPromedio: 1.0,
      pesoMaximo: 1.3,
      descripcionVenta: "Bandeja de chuletas",
    },
    {
      id: "cerdo-costillar-ahumado",
      nombre: "Costillar ahumado",
      tipo: "cerdo",
      precio: 9990,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Dark Pork · Costillar de Cerdo Ahumado · precio regular $9.990/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "premium",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 0.8,
      pesoPromedio: 1.3,
      pesoMaximo: 1.8,
      descripcionVenta: "Pieza ahumada",
    },
    {
      id: "cerdo-pulpa",
      nombre: "Pulpa de cerdo",
      tipo: "cerdo",
      precio: 6290,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Cerdo Supremo · Pulpa de Cerdo sin hueso 1 kg · $6.290/kg",
      parrilla: false,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.7,
      pesoMaximo: 2.3,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "cerdo-punta-ganso",
      nombre: "Punta de ganso de cerdo",
      tipo: "cerdo",
      precio: 7490,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Seara · Punta de Ganso de cerdo congelado · $7.490/kg",
      parrilla: false,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 0.9,
      pesoPromedio: 1.4,
      pesoMaximo: 1.9,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "cerdo-pierna",
      nombre: "Pierna de cerdo",
      tipo: "cerdo",
      precio: 7690,
      parrilla: false,
      conHueso: null,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 2.0,
      pesoMaximo: 2.8,
      descripcionVenta: "Trozo entero",
    },
    {
      id: "cerdo-pernil",
      nombre: "Pernil",
      tipo: "cerdo",
      precio: 8990,
      parrilla: false,
      conHueso: true,
      factorCompra: 1,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "peso_variable",
      pesoMinimo: 1.5,
      pesoPromedio: 2.5,
      pesoMaximo: 3.5,
      descripcionVenta: "Pieza grande",
    },
  ],

  pollo: [
    {
      id: "pollo-filetitos-pechuga",
      nombre: "Filetitos de pechuga",
      tipo: "pollo",
      precio: 8783,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Pollo · Filetito sin marinar 830 g · precio regular $7.290/pack ≈ $8.783/kg",
      parrilla: true,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.5,
      pesoPromedio: 0.8,
      pesoMaximo: 1.0,
      descripcionVenta: "Bandeja",
    },
    {
      id: "pollo-trutro-entero",
      nombre: "Trutro entero",
      tipo: "pollo",
      precio: 3890,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Ariztia · Trutro entero envasado · precio regular $3.890/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.7,
      pesoPromedio: 1.0,
      pesoMaximo: 1.4,
      descripcionVenta: "Bandeja",
    },
    {
      id: "pollo-trutro-corto",
      nombre: "Trutro corto",
      tipo: "pollo",
      precio: 4590,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Ariztia · Trutro corto envasado · precio regular $4.590/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.6,
      pesoPromedio: 0.9,
      pesoMaximo: 1.2,
      descripcionVenta: "Bandeja",
    },
    {
      id: "pollo-trutro-largo",
      nombre: "Trutro largo",
      tipo: "pollo",
      precio: 4190,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Pollo · Trutro largo envasado · precio regular $4.190/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "mixto",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.6,
      pesoPromedio: 0.9,
      pesoMaximo: 1.2,
      descripcionVenta: "Bandeja",
    },
    {
      id: "pollo-alitas",
      nombre: "Alitas",
      tipo: "pollo",
      precio: 5238,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Pollo · Alitas congeladas 800 g · precio regular $4.190/pack ≈ $5.238/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.6,
      pesoPromedio: 0.9,
      pesoMaximo: 1.2,
      descripcionVenta: "Bandeja",
    },
    {
      id: "pollo-entero",
      nombre: "Pollo entero",
      tipo: "pollo",
      precio: 3990,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Pollo · Pollo entero con menudencia · precio regular $3.990/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "unidad",
      pesoFormatoKg: 1.8,
      pesoMinimo: 1.4,
      pesoMaximo: 2.2,
      descripcionVenta: "Unidad entera",
    },
    {
      id: "pollo-pechuga-deshuesada",
      nombre: "Pechuga deshuesada",
      tipo: "pollo",
      precio: 8459,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Ariztia · Pechuga deshuesada envasada 850 g · precio regular $7.190/pack ≈ $8.459/kg",
      parrilla: true,
      conHueso: false,
      categoria: "premium",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.7,
      pesoPromedio: 1.0,
      pesoMaximo: 1.3,
      descripcionVenta: "Bandeja · sin hueso",
    },
    {
      id: "pollo-pechuga-hueso",
      nombre: "Pechuga entera con hueso",
      tipo: "pollo",
      precio: 5790,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Pollo · Pechuga entera envasada 1 kg · $5.790/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.1,
      pesoMaximo: 1.4,
      descripcionVenta: "Bandeja · pechuga entera con hueso",
    },
    {
      id: "pollo-trutro-ala",
      nombre: "Trutro ala",
      tipo: "pollo",
      precio: 6780,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Super Pollo · Trutro ala envasado 500 g · precio regular $3.390/pack = $6.780/kg",
      parrilla: true,
      conHueso: true,
      factorCompra: 1,
      categoria: "economico",
      unidadPrecio: "kg",
      formatoCompra: "bandeja",
      pesoMinimo: 0.5,
      pesoPromedio: 0.8,
      pesoMaximo: 1.0,
      descripcionVenta: "Bandeja",
    },
  ],

  embutidos: [
    {
      id: "embutidos-longaniza-parrillera",
      nombre: "Longaniza parrillera pack",
      tipo: "embutidos",
      precio: 6190,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Selección · Longaniza Parrillera 4 un, 500 g · $6.190/pack",
      parrilla: true,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "pack",
      formatoCompra: "pack",
      pesoFormatoKg: 0.5,
      unidadesPorPack: 4,
      descripcionVenta: "Pack de longanizas",
    },
    {
      id: "embutidos-chorizo-parrillero",
      nombre: "Chorizo parrillero pack",
      tipo: "embutidos",
      precio: 6590,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Selección · Chorizo Parrillero 8 un, 500 g · $6.590/pack",
      parrilla: true,
      conHueso: false,
      categoria: "mixto",
      unidadPrecio: "pack",
      formatoCompra: "pack",
      pesoFormatoKg: 0.5,
      unidadesPorPack: 8,
      descripcionVenta: "Pack de chorizos",
    },
    {
      id: "embutidos-prietas",
      nombre: "Prietas pack",
      tipo: "embutidos",
      precio: 2890,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Receta del Abuelo · Prieta Tradicional 3 un, 350 g · precio regular $2.890/pack",
      parrilla: true,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "pack",
      formatoCompra: "pack",
      pesoFormatoKg: 0.35,
      unidadesPorPack: 3,
      descripcionVenta: "Pack de prietas",
    },
    {
      id: "embutidos-salchicha-parrillera",
      nombre: "Salchicha parrillera pack",
      tipo: "embutidos",
      precio: 4290,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "La Preferida · Salchicha Sureña 10 un, 500 g · precio regular $4.290/pack",
      parrilla: true,
      conHueso: false,
      categoria: "economico",
      unidadPrecio: "pack",
      formatoCompra: "pack",
      pesoFormatoKg: 0.5,
      unidadesPorPack: 10,
      descripcionVenta: "Pack parrillero",
    },
    {
      id: "embutidos-butifarra",
      nombre: "Butifarra pack",
      tipo: "embutidos",
      precio: 6890,
      fechaPrecio: FECHA_REVISION_PRECIOS,
      fuentePrecio: "Lider.cl",
      referenciaPrecio: "Schwencke · Butifarra Parrillera Premium 8 un, 500 g · precio regular $6.890/pack",
      parrilla: true,
      conHueso: false,
      categoria: "premium",
      unidadPrecio: "pack",
      formatoCompra: "pack",
      pesoFormatoKg: 0.5,
      unidadesPorPack: 8,
      descripcionVenta: "Pack de butifarras",
    },
  ],
};

export const todosProductosAsado: ProductoAsado[] = [
  ...productosAsado.vacuno,
  ...productosAsado.cerdo,
  ...productosAsado.pollo,
  ...productosAsado.embutidos,
];

const productosPorId = new Map(
  todosProductosAsado.map((producto) => [producto.id, producto] as const),
);

const productosPorNombre = new Map(
  todosProductosAsado.map((producto) => [producto.nombre, producto] as const),
);

/**
 * Producto histórico retirado del selector porque el nombre "Pechuga" no
 * especificaba si correspondía a un corte con o sin hueso. Se conserva solo
 * para no alterar cálculos guardados previamente en localStorage.
 */
const productoLegacyPechuga: ProductoAsado = {
  id: "pollo-pechuga",
  nombre: "Pechuga (selección antigua)",
  tipo: "pollo",
  precio: 6650,
  parrilla: true,
  conHueso: null,
  categoria: "mixto",
  unidadPrecio: "kg",
  formatoCompra: "bandeja",
  pesoMinimo: 0.8,
  pesoPromedio: 1.0,
  pesoMaximo: 1.3,
  descripcionVenta: "Dato histórico sin especificación de hueso",
};

const referenciasHistoricas = new Map<string, ProductoAsado>([
  ["pollo-pechuga", productoLegacyPechuga],
  ["Pechuga", productoLegacyPechuga],
  ["Pechuga con hueso", productosPorId.get("pollo-pechuga-hueso")!],
]);

/**
 * Compatibilidad de migración:
 * acepta el ID estable, el nombre actual y referencias históricas guardadas
 * en localStorage.
 */
export function buscarProductoPorReferencia(
  referencia: string,
): ProductoAsado | undefined {
  return (
    productosPorId.get(referencia) ??
    productosPorNombre.get(referencia) ??
    referenciasHistoricas.get(referencia)
  );
}

export function normalizarReferenciaProducto(referencia: string): string {
  return buscarProductoPorReferencia(referencia)?.id ?? referencia;
}
