export type CategoriaCorte = "economico" | "mixto" | "premium";
export type TipoCarne = "vacuno" | "cerdo" | "pollo" | "embutidos";
export type TipoVenta = "peso_variable" | "bandeja" | "pack" | "unidad";

export interface ProductoAsado {
  nombre: string;
  tipo: TipoCarne;
  precio: number;
  parrilla: boolean;
  categoria: CategoriaCorte;
  tipoVenta: TipoVenta;
  pesoMinimo?: number;
  pesoPromedio?: number;
  pesoMaximo?: number;
  unidadesPorPack?: number;
  rendimiento?: number;
  descripcionVenta?: string;
}

export interface ProductosAsado {
  vacuno: ProductoAsado[];
  cerdo: ProductoAsado[];
  pollo: ProductoAsado[];
  embutidos: ProductoAsado[];
}

export const productosAsado: ProductosAsado = {
  vacuno: [
    {
      nombre: "Lomo vetado al vacío",
      tipo: "vacuno",
      precio: 18590,
      parrilla: true,
      categoria: "premium",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 1.8,
      pesoMaximo: 2.5,
      rendimiento: 0.9,
      descripcionVenta: "Pieza al vacío",
    },
    {
      nombre: "Lomo liso al vacío",
      tipo: "vacuno",
      precio: 13990,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 1.7,
      pesoMaximo: 2.3,
      rendimiento: 0.9,
      descripcionVenta: "Pieza al vacío",
    },
    {
      nombre: "Sobrecostilla",
      tipo: "vacuno",
      precio: 8790,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.1,
      pesoMaximo: 1.5,
      rendimiento: 0.82,
      descripcionVenta: "Bandeja o trozo",
    },
    {
      nombre: "Huachalomo",
      tipo: "vacuno",
      precio: 8790,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.2,
      pesoMaximo: 1.6,
      rendimiento: 0.82,
      descripcionVenta: "Bandeja o trozo",
    },
    {
      nombre: "Asado del carnicero",
      tipo: "vacuno",
      precio: 8790,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.9,
      pesoPromedio: 1.3,
      pesoMaximo: 1.8,
      rendimiento: 0.8,
      descripcionVenta: "Trozo para parrilla",
    },
    {
      nombre: "Punta picana",
      tipo: "vacuno",
      precio: 14390,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.5,
      pesoMaximo: 2.0,
      rendimiento: 0.87,
      descripcionVenta: "Pieza entera o media pieza",
    },
    {
      nombre: "Filete",
      tipo: "vacuno",
      precio: 18990,
      parrilla: true,
      categoria: "premium",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.6,
      pesoMaximo: 2.1,
      rendimiento: 0.92,
      descripcionVenta: "Pieza al vacío",
    },
    {
      nombre: "Punta de ganso",
      tipo: "vacuno",
      precio: 13990,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.4,
      pesoMaximo: 1.9,
      rendimiento: 0.86,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Entraña",
      tipo: "vacuno",
      precio: 16990,
      parrilla: true,
      categoria: "premium",
      tipoVenta: "bandeja",
      pesoMinimo: 0.4,
      pesoPromedio: 0.7,
      pesoMaximo: 1.0,
      rendimiento: 0.78,
      descripcionVenta: "Bandeja o pieza delgada",
    },
    {
      nombre: "Tapabarriga",
      tipo: "vacuno",
      precio: 12190,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.2,
      pesoMaximo: 1.6,
      rendimiento: 0.8,
      descripcionVenta: "Trozo para parrilla",
    },
    {
      nombre: "Choclillo",
      tipo: "vacuno",
      precio: 11190,
      parrilla: false,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.6,
      pesoMaximo: 2.2,
      rendimiento: 0.88,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Ganso",
      tipo: "vacuno",
      precio: 8990,
      parrilla: false,
      categoria: "economico",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.1,
      pesoPromedio: 1.8,
      pesoMaximo: 2.5,
      rendimiento: 0.87,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Posta rosada",
      tipo: "vacuno",
      precio: 8490,
      parrilla: false,
      categoria: "economico",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.7,
      pesoMaximo: 2.3,
      rendimiento: 0.9,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Asiento",
      tipo: "vacuno",
      precio: 12990,
      parrilla: false,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.1,
      pesoPromedio: 1.8,
      pesoMaximo: 2.4,
      rendimiento: 0.88,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Plateada",
      tipo: "vacuno",
      precio: 11990,
      parrilla: false,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.6,
      pesoMaximo: 2.1,
      rendimiento: 0.78,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Tapapecho",
      tipo: "vacuno",
      precio: 10990,
      parrilla: false,
      categoria: "economico",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 2.0,
      pesoMaximo: 2.8,
      rendimiento: 0.72,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Punta paleta",
      tipo: "vacuno",
      precio: 10490,
      parrilla: false,
      categoria: "economico",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.6,
      pesoMaximo: 2.2,
      rendimiento: 0.84,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Posta negra",
      tipo: "vacuno",
      precio: 10990,
      parrilla: false,
      categoria: "economico",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.7,
      pesoMaximo: 2.3,
      rendimiento: 0.88,
      descripcionVenta: "Trozo entero",
    },
  ],

  cerdo: [
    {
      nombre: "Costillar de cerdo",
      tipo: "cerdo",
      precio: 9590,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 1.8,
      pesoMaximo: 2.5,
      rendimiento: 0.65,
      descripcionVenta: "Costillar entero o medio costillar",
    },
    {
      nombre: "Lomo de cerdo",
      tipo: "cerdo",
      precio: 7990,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.5,
      pesoMaximo: 2.0,
      rendimiento: 0.9,
      descripcionVenta: "Pieza entera",
    },
    {
      nombre: "Malaya de cerdo",
      tipo: "cerdo",
      precio: 14975,
      parrilla: true,
      categoria: "premium",
      tipoVenta: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.2,
      pesoMaximo: 1.6,
      rendimiento: 0.72,
      descripcionVenta: "Bandeja o trozo",
    },
    {
      nombre: "Chuleta vetada",
      tipo: "cerdo",
      precio: 8990,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "bandeja",
      pesoMinimo: 0.7,
      pesoPromedio: 1.0,
      pesoMaximo: 1.4,
      rendimiento: 0.82,
      descripcionVenta: "Bandeja de chuletas",
    },
    {
      nombre: "Chuleta centro",
      tipo: "cerdo",
      precio: 8290,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.7,
      pesoPromedio: 1.0,
      pesoMaximo: 1.3,
      rendimiento: 0.8,
      descripcionVenta: "Bandeja de chuletas",
    },
    {
      nombre: "Costillar ahumado",
      tipo: "cerdo",
      precio: 10990,
      parrilla: true,
      categoria: "premium",
      tipoVenta: "peso_variable",
      pesoMinimo: 0.8,
      pesoPromedio: 1.3,
      pesoMaximo: 1.8,
      rendimiento: 0.68,
      descripcionVenta: "Pieza ahumada",
    },
    {
      nombre: "Pulpa de cerdo",
      tipo: "cerdo",
      precio: 8990,
      parrilla: false,
      categoria: "economico",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.0,
      pesoPromedio: 1.7,
      pesoMaximo: 2.3,
      rendimiento: 0.9,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Punta de ganso de cerdo",
      tipo: "cerdo",
      precio: 8490,
      parrilla: false,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 0.9,
      pesoPromedio: 1.4,
      pesoMaximo: 1.9,
      rendimiento: 0.87,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Pierna de cerdo",
      tipo: "cerdo",
      precio: 7690,
      parrilla: false,
      categoria: "economico",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.2,
      pesoPromedio: 2.0,
      pesoMaximo: 2.8,
      rendimiento: 0.85,
      descripcionVenta: "Trozo entero",
    },
    {
      nombre: "Pernil",
      tipo: "cerdo",
      precio: 8990,
      parrilla: false,
      categoria: "mixto",
      tipoVenta: "peso_variable",
      pesoMinimo: 1.5,
      pesoPromedio: 2.5,
      pesoMaximo: 3.5,
      rendimiento: 0.78,
      descripcionVenta: "Pieza grande",
    },
  ],

  pollo: [
    {
      nombre: "Pechuga",
      tipo: "pollo",
      precio: 6650,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.0,
      pesoMaximo: 1.3,
      rendimiento: 0.92,
      descripcionVenta: "Bandeja",
    },
    {
      nombre: "Filetitos de pechuga",
      tipo: "pollo",
      precio: 6990,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "bandeja",
      pesoMinimo: 0.5,
      pesoPromedio: 0.8,
      pesoMaximo: 1.0,
      rendimiento: 0.95,
      descripcionVenta: "Bandeja",
    },
    {
      nombre: "Trutro entero",
      tipo: "pollo",
      precio: 5790,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.7,
      pesoPromedio: 1.0,
      pesoMaximo: 1.4,
      rendimiento: 0.72,
      descripcionVenta: "Bandeja",
    },
    {
      nombre: "Trutro corto",
      tipo: "pollo",
      precio: 5790,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.6,
      pesoPromedio: 0.9,
      pesoMaximo: 1.2,
      rendimiento: 0.7,
      descripcionVenta: "Bandeja",
    },
    {
      nombre: "Trutro largo",
      tipo: "pollo",
      precio: 5890,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "bandeja",
      pesoMinimo: 0.6,
      pesoPromedio: 0.9,
      pesoMaximo: 1.2,
      rendimiento: 0.72,
      descripcionVenta: "Bandeja",
    },
    {
      nombre: "Alitas",
      tipo: "pollo",
      precio: 4990,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.6,
      pesoPromedio: 0.9,
      pesoMaximo: 1.2,
      rendimiento: 0.52,
      descripcionVenta: "Bandeja",
    },
    {
      nombre: "Pollo entero",
      tipo: "pollo",
      precio: 3790,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "unidad",
      pesoMinimo: 1.4,
      pesoPromedio: 1.8,
      pesoMaximo: 2.2,
      rendimiento: 0.68,
      descripcionVenta: "Unidad entera",
    },
    {
      nombre: "Pechuga deshuesada",
      tipo: "pollo",
      precio: 6990,
      parrilla: true,
      categoria: "premium",
      tipoVenta: "bandeja",
      pesoMinimo: 0.7,
      pesoPromedio: 1.0,
      pesoMaximo: 1.3,
      rendimiento: 0.96,
      descripcionVenta: "Bandeja",
    },
    {
      nombre: "Pechuga con hueso",
      tipo: "pollo",
      precio: 5490,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.8,
      pesoPromedio: 1.1,
      pesoMaximo: 1.4,
      rendimiento: 0.74,
      descripcionVenta: "Bandeja",
    },
    {
      nombre: "Trutro ala",
      tipo: "pollo",
      precio: 4690,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "bandeja",
      pesoMinimo: 0.5,
      pesoPromedio: 0.8,
      pesoMaximo: 1.0,
      rendimiento: 0.55,
      descripcionVenta: "Bandeja",
    },
  ],

  embutidos: [
    {
      nombre: "Longaniza parrillera pack",
      tipo: "embutidos",
      precio: 6990,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "pack",
      pesoMinimo: 0.45,
      pesoPromedio: 0.7,
      pesoMaximo: 0.9,
      unidadesPorPack: 6,
      rendimiento: 0.95,
      descripcionVenta: "Pack de longanizas",
    },
    {
      nombre: "Chorizo parrillero pack",
      tipo: "embutidos",
      precio: 7990,
      parrilla: true,
      categoria: "mixto",
      tipoVenta: "pack",
      pesoMinimo: 0.45,
      pesoPromedio: 0.75,
      pesoMaximo: 0.95,
      unidadesPorPack: 5,
      rendimiento: 0.95,
      descripcionVenta: "Pack de chorizos",
    },
    {
      nombre: "Prietas pack",
      tipo: "embutidos",
      precio: 5490,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "pack",
      pesoMinimo: 0.4,
      pesoPromedio: 0.65,
      pesoMaximo: 0.85,
      unidadesPorPack: 4,
      rendimiento: 0.92,
      descripcionVenta: "Pack de prietas",
    },
    {
      nombre: "Salchicha parrillera pack",
      tipo: "embutidos",
      precio: 4990,
      parrilla: true,
      categoria: "economico",
      tipoVenta: "pack",
      pesoMinimo: 0.4,
      pesoPromedio: 0.7,
      pesoMaximo: 0.9,
      unidadesPorPack: 6,
      rendimiento: 0.93,
      descripcionVenta: "Pack parrillero",
    },
    {
      nombre: "Butifarra pack",
      tipo: "embutidos",
      precio: 7590,
      parrilla: true,
      categoria: "premium",
      tipoVenta: "pack",
      pesoMinimo: 0.4,
      pesoPromedio: 0.65,
      pesoMaximo: 0.85,
      unidadesPorPack: 5,
      rendimiento: 0.94,
      descripcionVenta: "Pack de butifarras",
    },
  ],
};

// export type CategoriaCorte = "economico" | "mixto" | "premium";
// export type TipoCarne = "vacuno" | "cerdo" | "pollo" | "embutidos";
// export type TipoVenta = "peso_variable" | "bandeja" | "pack" | "unidad";

// export interface ProductoAsado {
//   nombre: string;
//   tipo: TipoCarne;
//   precio: number; // precio referencial por kg o por pack, según tipoVenta
//   parrilla: boolean;
//   categoria: CategoriaCorte;

//   // Nueva lógica para compra real
//   tipoVenta: TipoVenta;

//   // Pesos en kg
//   pesoMinimo?: number;
//   pesoPromedio?: number;
//   pesoMaximo?: number;

//   // Para productos por pack
//   unidadesPorPack?: number;

//   // Qué tan aprovechable es el producto como carne comestible
//   // ejemplo: costillar/embutidos tienen distinto rendimiento
//   rendimiento?: number;

//   // ayuda visual / lógica futura
//   descripcionVenta?: string;
// }


// export interface ProductosAsado {
//   vacuno: ProductoAsado[];
//   cerdo: ProductoAsado[];
//   pollo: ProductoAsado[];
//   embutidos: ProductoAsado[];
// }

// export const productosAsado: ProductosAsado = {
//   vacuno: [
//     {
//       nombre: "Lomo vetado al vacío",
//       tipo: "vacuno",
//       precio: 18590,
//       parrilla: true,
//       categoria: "premium",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.2,
//       pesoPromedio: 1.8,
//       pesoMaximo: 2.5,
//       rendimiento: 0.9,
//       descripcionVenta: "Pieza al vacío",
//     },
//     {
//       nombre: "Lomo liso al vacío",
//       tipo: "vacuno",
//       precio: 13990,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.2,
//       pesoPromedio: 1.7,
//       pesoMaximo: 2.3,
//       rendimiento: 0.9,
//       descripcionVenta: "Pieza al vacío",
//     },
//     {
//       nombre: "Sobrecostilla",
//       tipo: "vacuno",
//       precio: 8790,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.8,
//       pesoPromedio: 1.1,
//       pesoMaximo: 1.5,
//       rendimiento: 0.82,
//       descripcionVenta: "Bandeja o trozo",
//     },
//     {
//       nombre: "Huachalomo",
//       tipo: "vacuno",
//       precio: 8790,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.8,
//       pesoPromedio: 1.2,
//       pesoMaximo: 1.6,
//       rendimiento: 0.82,
//       descripcionVenta: "Bandeja o trozo",
//     },
//     {
//       nombre: "Asado del carnicero",
//       tipo: "vacuno",
//       precio: 8790,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.9,
//       pesoPromedio: 1.3,
//       pesoMaximo: 1.8,
//       rendimiento: 0.8,
//       descripcionVenta: "Trozo para parrilla",
//     },
//     {
//       nombre: "Punta picana",
//       tipo: "vacuno",
//       precio: 14390,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.5,
//       pesoMaximo: 2.0,
//       rendimiento: 0.87,
//       descripcionVenta: "Pieza entera o media pieza",
//     },
//     {
//       nombre: "Filete",
//       tipo: "vacuno",
//       precio: 18990,
//       parrilla: true,
//       categoria: "premium",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.6,
//       pesoMaximo: 2.1,
//       rendimiento: 0.92,
//       descripcionVenta: "Pieza al vacío",
//     },
//     {
//       nombre: "Punta de ganso",
//       tipo: "vacuno",
//       precio: 13990,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.4,
//       pesoMaximo: 1.9,
//       rendimiento: 0.86,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Entraña",
//       tipo: "vacuno",
//       precio: 16990,
//       parrilla: true,
//       categoria: "premium",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.4,
//       pesoPromedio: 0.7,
//       pesoMaximo: 1.0,
//       rendimiento: 0.78,
//       descripcionVenta: "Bandeja o pieza delgada",
//     },
//     {
//       nombre: "Tapabarriga",
//       tipo: "vacuno",
//       precio: 12190,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.8,
//       pesoPromedio: 1.2,
//       pesoMaximo: 1.6,
//       rendimiento: 0.8,
//       descripcionVenta: "Trozo para parrilla",
//     },
//     {
//       nombre: "Choclillo",
//       tipo: "vacuno",
//       precio: 11190,
//       parrilla: false,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.6,
//       pesoMaximo: 2.2,
//       rendimiento: 0.88,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Ganso",
//       tipo: "vacuno",
//       precio: 8990,
//       parrilla: false,
//       categoria: "economico",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.1,
//       pesoPromedio: 1.8,
//       pesoMaximo: 2.5,
//       rendimiento: 0.87,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Posta rosada",
//       tipo: "vacuno",
//       precio: 8490,
//       parrilla: false,
//       categoria: "economico",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.7,
//       pesoMaximo: 2.3,
//       rendimiento: 0.9,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Asiento",
//       tipo: "vacuno",
//       precio: 12990,
//       parrilla: false,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.1,
//       pesoPromedio: 1.8,
//       pesoMaximo: 2.4,
//       rendimiento: 0.88,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Plateada",
//       tipo: "vacuno",
//       precio: 11990,
//       parrilla: false,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.6,
//       pesoMaximo: 2.1,
//       rendimiento: 0.78,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Tapapecho",
//       tipo: "vacuno",
//       precio: 10990,
//       parrilla: false,
//       categoria: "economico",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.2,
//       pesoPromedio: 2.0,
//       pesoMaximo: 2.8,
//       rendimiento: 0.72,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Punta paleta",
//       tipo: "vacuno",
//       precio: 10490,
//       parrilla: false,
//       categoria: "economico",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.6,
//       pesoMaximo: 2.2,
//       rendimiento: 0.84,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Posta negra",
//       tipo: "vacuno",
//       precio: 10990,
//       parrilla: false,
//       categoria: "economico",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.7,
//       pesoMaximo: 2.3,
//       rendimiento: 0.88,
//       descripcionVenta: "Trozo entero",
//     },
//   ],

//   cerdo: [
//     {
//       nombre: "Costillar de cerdo",
//       tipo: "cerdo",
//       precio: 9590,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.2,
//       pesoPromedio: 1.8,
//       pesoMaximo: 2.5,
//       rendimiento: 0.65,
//       descripcionVenta: "Costillar entero o medio costillar",
//     },
//     {
//       nombre: "Lomo de cerdo",
//       tipo: "cerdo",
//       precio: 7990,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.5,
//       pesoMaximo: 2.0,
//       rendimiento: 0.9,
//       descripcionVenta: "Pieza entera",
//     },
//     {
//       nombre: "Malaya de cerdo",
//       tipo: "cerdo",
//       precio: 14975,
//       parrilla: true,
//       categoria: "premium",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.8,
//       pesoPromedio: 1.2,
//       pesoMaximo: 1.6,
//       rendimiento: 0.72,
//       descripcionVenta: "Bandeja o trozo",
//     },
//     {
//       nombre: "Chuleta vetada",
//       tipo: "cerdo",
//       precio: 8990,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.7,
//       pesoPromedio: 1.0,
//       pesoMaximo: 1.4,
//       rendimiento: 0.82,
//       descripcionVenta: "Bandeja de chuletas",
//     },
//     {
//       nombre: "Chuleta centro",
//       tipo: "cerdo",
//       precio: 8290,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.7,
//       pesoPromedio: 1.0,
//       pesoMaximo: 1.3,
//       rendimiento: 0.8,
//       descripcionVenta: "Bandeja de chuletas",
//     },
//     {
//       nombre: "Costillar ahumado",
//       tipo: "cerdo",
//       precio: 10990,
//       parrilla: true,
//       categoria: "premium",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 0.8,
//       pesoPromedio: 1.3,
//       pesoMaximo: 1.8,
//       rendimiento: 0.68,
//       descripcionVenta: "Pieza ahumada",
//     },
//     {
//       nombre: "Pulpa de cerdo",
//       tipo: "cerdo",
//       precio: 8990,
//       parrilla: false,
//       categoria: "economico",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.0,
//       pesoPromedio: 1.7,
//       pesoMaximo: 2.3,
//       rendimiento: 0.9,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Punta de ganso de cerdo",
//       tipo: "cerdo",
//       precio: 8490,
//       parrilla: false,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 0.9,
//       pesoPromedio: 1.4,
//       pesoMaximo: 1.9,
//       rendimiento: 0.87,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Pierna de cerdo",
//       tipo: "cerdo",
//       precio: 7690,
//       parrilla: false,
//       categoria: "economico",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.2,
//       pesoPromedio: 2.0,
//       pesoMaximo: 2.8,
//       rendimiento: 0.85,
//       descripcionVenta: "Trozo entero",
//     },
//     {
//       nombre: "Pernil",
//       tipo: "cerdo",
//       precio: 8990,
//       parrilla: false,
//       categoria: "mixto",
//       tipoVenta: "peso_variable",
//       pesoMinimo: 1.5,
//       pesoPromedio: 2.5,
//       pesoMaximo: 3.5,
//       rendimiento: 0.78,
//       descripcionVenta: "Pieza grande",
//     },
//   ],

//   pollo: [
//     {
//       nombre: "Pechuga",
//       tipo: "pollo",
//       precio: 6650,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.8,
//       pesoPromedio: 1.0,
//       pesoMaximo: 1.3,
//       rendimiento: 0.92,
//       descripcionVenta: "Bandeja",
//     },
//     {
//       nombre: "Filetitos de pechuga",
//       tipo: "pollo",
//       precio: 6990,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.5,
//       pesoPromedio: 0.8,
//       pesoMaximo: 1.0,
//       rendimiento: 0.95,
//       descripcionVenta: "Bandeja",
//     },
//     {
//       nombre: "Trutro entero",
//       tipo: "pollo",
//       precio: 5790,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.7,
//       pesoPromedio: 1.0,
//       pesoMaximo: 1.4,
//       rendimiento: 0.72,
//       descripcionVenta: "Bandeja",
//     },
//     {
//       nombre: "Trutro corto",
//       tipo: "pollo",
//       precio: 5790,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.6,
//       pesoPromedio: 0.9,
//       pesoMaximo: 1.2,
//       rendimiento: 0.7,
//       descripcionVenta: "Bandeja",
//     },
//     {
//       nombre: "Trutro largo",
//       tipo: "pollo",
//       precio: 5890,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.6,
//       pesoPromedio: 0.9,
//       pesoMaximo: 1.2,
//       rendimiento: 0.72,
//       descripcionVenta: "Bandeja",
//     },
//     {
//       nombre: "Alitas",
//       tipo: "pollo",
//       precio: 4990,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.6,
//       pesoPromedio: 0.9,
//       pesoMaximo: 1.2,
//       rendimiento: 0.52,
//       descripcionVenta: "Bandeja",
//     },
//     {
//       nombre: "Pollo entero",
//       tipo: "pollo",
//       precio: 3790,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "unidad",
//       pesoMinimo: 1.4,
//       pesoPromedio: 1.8,
//       pesoMaximo: 2.2,
//       rendimiento: 0.68,
//       descripcionVenta: "Unidad entera",
//     },
//     {
//       nombre: "Pechuga deshuesada",
//       tipo: "pollo",
//       precio: 6990,
//       parrilla: true,
//       categoria: "premium",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.7,
//       pesoPromedio: 1.0,
//       pesoMaximo: 1.3,
//       rendimiento: 0.96,
//       descripcionVenta: "Bandeja",
//     },
//     {
//       nombre: "Pechuga con hueso",
//       tipo: "pollo",
//       precio: 5490,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.8,
//       pesoPromedio: 1.1,
//       pesoMaximo: 1.4,
//       rendimiento: 0.74,
//       descripcionVenta: "Bandeja",
//     },
//     {
//       nombre: "Trutro ala",
//       tipo: "pollo",
//       precio: 4690,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "bandeja",
//       pesoMinimo: 0.5,
//       pesoPromedio: 0.8,
//       pesoMaximo: 1.0,
//       rendimiento: 0.55,
//       descripcionVenta: "Bandeja",
//     },
//   ],

//   embutidos: [
//     {
//       nombre: "Longaniza parrillera pack",
//       tipo: "embutidos",
//       precio: 6990,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "pack",
//       pesoMinimo: 0.45,
//       pesoPromedio: 0.7,
//       pesoMaximo: 0.9,
//       unidadesPorPack: 6,
//       rendimiento: 0.95,
//       descripcionVenta: "Pack de longanizas",
//     },
//     {
//       nombre: "Chorizo parrillero pack",
//       tipo: "embutidos",
//       precio: 7990,
//       parrilla: true,
//       categoria: "mixto",
//       tipoVenta: "pack",
//       pesoMinimo: 0.45,
//       pesoPromedio: 0.75,
//       pesoMaximo: 0.95,
//       unidadesPorPack: 5,
//       rendimiento: 0.95,
//       descripcionVenta: "Pack de chorizos",
//     },
//     {
//       nombre: "Prietas pack",
//       tipo: "embutidos",
//       precio: 5490,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "pack",
//       pesoMinimo: 0.4,
//       pesoPromedio: 0.65,
//       pesoMaximo: 0.85,
//       unidadesPorPack: 4,
//       rendimiento: 0.92,
//       descripcionVenta: "Pack de prietas",
//     },
//     {
//       nombre: "Salchicha parrillera pack",
//       tipo: "embutidos",
//       precio: 4990,
//       parrilla: true,
//       categoria: "economico",
//       tipoVenta: "pack",
//       pesoMinimo: 0.4,
//       pesoPromedio: 0.7,
//       pesoMaximo: 0.9,
//       unidadesPorPack: 6,
//       rendimiento: 0.93,
//       descripcionVenta: "Pack parrillero",
//     },
//     {
//       nombre: "Butifarra pack",
//       tipo: "embutidos",
//       precio: 7590,
//       parrilla: true,
//       categoria: "premium",
//       tipoVenta: "pack",
//       pesoMinimo: 0.4,
//       pesoPromedio: 0.65,
//       pesoMaximo: 0.85,
//       unidadesPorPack: 5,
//       rendimiento: 0.94,
//       descripcionVenta: "Pack de butifarras",
//     },
//   ],
// };
// // export type CategoriaCorte = "economico" | "mixto" | "premium";

// // export interface Corte {
// //   nombre: string;
// //   precio: number;
// //   parrilla: boolean;
// //   categoria: CategoriaCorte;
// // }

// // export interface Carnes {
// //   vacuno: Corte[];
// //   cerdo: Corte[];
// //   pollo: Corte[];
// // }

// // export const carnes: Carnes = {
// //   vacuno: [
// //     { nombre: "Lomo vetado", precio: 18590, parrilla: true, categoria: "premium" },
// //     { nombre: "Lomo liso", precio: 13990, parrilla: true, categoria: "mixto" },
// //     { nombre: "Sobrecostilla", precio: 8790, parrilla: true, categoria: "economico" },
// //     { nombre: "Huachalomo", precio: 8790, parrilla: true, categoria: "economico" },
// //     { nombre: "Asado del carnicero", precio: 8790, parrilla: true, categoria: "economico" },
// //     { nombre: "Punta picana", precio: 14390, parrilla: true, categoria: "mixto" },
// //     { nombre: "Filete", precio: 18990, parrilla: true, categoria: "premium" },
// //     { nombre: "Punta de ganso", precio: 13990, parrilla: true, categoria: "mixto" },
// //     { nombre: "Entraña", precio: 16990, parrilla: true, categoria: "premium" },
// //     { nombre: "Tapabarriga", precio: 12190, parrilla: true, categoria: "mixto" },

// //     { nombre: "Choclillo", precio: 11190, parrilla: false, categoria: "mixto" },
// //     { nombre: "Ganso", precio: 8990, parrilla: false, categoria: "economico" },
// //     { nombre: "Posta rosada", precio: 8490, parrilla: false, categoria: "economico" },
// //     { nombre: "Asiento", precio: 12990, parrilla: false, categoria: "mixto" },
// //     { nombre: "Plateada", precio: 11990, parrilla: false, categoria: "mixto" },
// //     { nombre: "Tapapecho", precio: 10990, parrilla: false, categoria: "economico" },
// //     { nombre: "Punta paleta", precio: 10490, parrilla: false, categoria: "economico" },
// //     { nombre: "Posta negra", precio: 10990, parrilla: false, categoria: "economico" },
// //   ],

// //   cerdo: [
// //     { nombre: "Costillar", precio: 9590, parrilla: true, categoria: "economico" },
// //     { nombre: "Lomo", precio: 7990, parrilla: true, categoria: "mixto" },
// //     { nombre: "Malaya", precio: 14975, parrilla: true, categoria: "premium" },
// //     { nombre: "Chuleta vetada", precio: 8990, parrilla: true, categoria: "mixto" },
// //     { nombre: "Chuleta centro", precio: 8290, parrilla: true, categoria: "economico" },
// //     { nombre: "Costillar ahumado", precio: 10990, parrilla: true, categoria: "premium" },

// //     { nombre: "Pulpa de cerdo", precio: 8990, parrilla: false, categoria: "economico" },
// //     { nombre: "Punta de ganso de cerdo", precio: 8490, parrilla: false, categoria: "mixto" },
// //     { nombre: "Pierna de cerdo", precio: 7690, parrilla: false, categoria: "economico" },
// //     { nombre: "Pernil", precio: 8990, parrilla: false, categoria: "mixto" },
// //   ],

// //   pollo: [
// //     { nombre: "Pechuga", precio: 6650, parrilla: true, categoria: "mixto" },
// //     { nombre: "Filetitos de pechuga", precio: 6990, parrilla: true, categoria: "mixto" },
// //     { nombre: "Trutro entero", precio: 5790, parrilla: true, categoria: "economico" },
// //     { nombre: "Trutro corto", precio: 5790, parrilla: true, categoria: "economico" },
// //     { nombre: "Trutro largo", precio: 5890, parrilla: true, categoria: "mixto" },
// //     { nombre: "Alitas", precio: 4990, parrilla: true, categoria: "economico" },
// //     { nombre: "Pollo entero", precio: 3790, parrilla: true, categoria: "economico" },
// //     { nombre: "Pechuga deshuesada", precio: 6990, parrilla: true, categoria: "premium" },
// //     { nombre: "Pechuga con hueso", precio: 5490, parrilla: true, categoria: "economico" },
// //     { nombre: "Trutro ala", precio: 4690, parrilla: true, categoria: "economico" },
// //   ],
// // };
// // // export interface Corte {
// // //   nombre: string;
// // //   precio: number;
// // //   parrilla: boolean;
// // // }

// // // export interface Carnes {
// // //   vacuno: Corte[];
// // //   cerdo: Corte[];
// // //   pollo: Corte[];
// // // }

// // // export const carnes: Carnes = {
// // //   vacuno: [
// // //     { nombre: "Lomo vetado", precio: 18590, parrilla: true },
// // //     { nombre: "Lomo liso", precio: 13990, parrilla: true },
// // //     { nombre: "Sobrecostilla", precio: 8790, parrilla: true },
// // //     { nombre: "Huachalomo", precio: 8790, parrilla: true },
// // //     { nombre: "Asado del carnicero", precio: 8790, parrilla: true },
// // //     { nombre: "Punta picana", precio: 14390, parrilla: true },
// // //     { nombre: "Filete", precio: 18990, parrilla: true },
// // //     { nombre: "Punta de ganso", precio: 13990, parrilla: true },
// // //     { nombre: "Entraña", precio: 16990, parrilla: true },
// // //     { nombre: "Tapabarriga", precio: 12190, parrilla: true },

// // //     { nombre: "Choclillo", precio: 11190, parrilla: false },
// // //     { nombre: "Ganso", precio: 8990, parrilla: false },
// // //     { nombre: "Posta rosada", precio: 8490, parrilla: false },
// // //     { nombre: "Asiento", precio: 12990, parrilla: false },
// // //     { nombre: "Plateada", precio: 11990, parrilla: false },
// // //     { nombre: "Tapapecho", precio: 10990, parrilla: false },
// // //     { nombre: "Punta paleta", precio: 10490, parrilla: false },
// // //     { nombre: "Posta negra", precio: 10990, parrilla: false },
// // //   ],

// // //   cerdo: [
// // //     { nombre: "Costillar", precio: 9590, parrilla: true },
// // //     { nombre: "Lomo", precio: 7990, parrilla: true },
// // //     { nombre: "Malaya", precio: 14975, parrilla: true },
// // //     { nombre: "Chuleta vetada", precio: 8990, parrilla: true },
// // //     { nombre: "Chuleta centro", precio: 8290, parrilla: true },
// // //     { nombre: "Costillar ahumado", precio: 10990, parrilla: true },

// // //     { nombre: "Pulpa de cerdo", precio: 8990, parrilla: false },
// // //     { nombre: "Punta de ganso de cerdo", precio: 8490, parrilla: false },
// // //     { nombre: "Pierna de cerdo", precio: 7690, parrilla: false },
// // //     { nombre: "Pernil", precio: 8990, parrilla: false },
// // //   ],

// // //   pollo: [
// // //     { nombre: "Pechuga", precio: 6650, parrilla: true },
// // //     { nombre: "Filetitos de pechuga", precio: 6990, parrilla: true },
// // //     { nombre: "Trutro entero", precio: 5790, parrilla: true },
// // //     { nombre: "Trutro corto", precio: 5790, parrilla: true },
// // //     { nombre: "Trutro largo", precio: 5890, parrilla: true },
// // //     { nombre: "Alitas", precio: 4990, parrilla: true },
// // //     { nombre: "Pollo entero", precio: 3790, parrilla: true },
// // //     { nombre: "Pechuga deshuesada", precio: 6990, parrilla: true },
// // //     { nombre: "Pechuga con hueso", precio: 5490, parrilla: true },
// // //     { nombre: "Trutro ala", precio: 4690, parrilla: true },
// // //   ],
// // // };